# Generated by Django 5.2.8 on 2025-11-25 13:35

import contacts.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('street_number', models.CharField(max_length=50)),
                ('city_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('customer_id', models.CharField(db_index=True, default=contacts.models.generate_customer_id, editable=False, help_text='Automatically generated unique customer identifier', max_length=100, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='contacts.address')),
            ],
            options={
                'db_table': 'appuser',
            },
        ),
        migrations.CreateModel(
            name='CustomerRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(db_index=True, default=0)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('appuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relationship', to='contacts.appuser')),
            ],
            options={
                'db_table': 'customer_relationship',
            },
        ),
    ]
