# Generated by Django 5.2.8 on 2025-11-25 19:02

import contacts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='birthday',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='customer_id',
            field=models.CharField(db_index=True, default=contacts.models.generate_customer_id, editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], db_index=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['city'], name='address_city_db657e_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['country'], name='address_country_dd48a9_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['city_code'], name='address_city_co_84058d_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['street'], name='address_street_06192f_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['street_number'], name='address_street__3daf37_idx'),
        ),
        migrations.AddIndex(
            model_name='appuser',
            index=models.Index(fields=['first_name', 'last_name'], name='appuser_first_n_d046b2_idx'),
        ),
        migrations.AddIndex(
            model_name='appuser',
            index=models.Index(fields=['address', 'last_name'], name='appuser_address_20fd43_idx'),
        ),
        migrations.AddIndex(
            model_name='appuser',
            index=models.Index(fields=['created'], name='appuser_created_3324af_idx'),
        ),
        migrations.AddIndex(
            model_name='appuser',
            index=models.Index(fields=['last_updated'], name='appuser_last_up_a565c4_idx'),
        ),
        migrations.AddIndex(
            model_name='customerrelationship',
            index=models.Index(fields=['appuser'], name='customer_re_appuser_1d4254_idx'),
        ),
        migrations.AddIndex(
            model_name='customerrelationship',
            index=models.Index(fields=['points'], name='customer_re_points_149dae_idx'),
        ),
        migrations.AddIndex(
            model_name='customerrelationship',
            index=models.Index(fields=['created'], name='customer_re_created_4d9583_idx'),
        ),
        migrations.AddIndex(
            model_name='customerrelationship',
            index=models.Index(fields=['last_activity'], name='customer_re_last_ac_78a740_idx'),
        ),
    ]
