# Generated by Django 5.2.8 on 2025-11-25 22:21

import contacts.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_appuser_birthday_alter_appuser_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='address',
            name='address_city_co_84058d_idx',
        ),
        migrations.RemoveIndex(
            model_name='address',
            name='address_street_06192f_idx',
        ),
        migrations.RemoveIndex(
            model_name='address',
            name='address_street__3daf37_idx',
        ),
        migrations.RemoveIndex(
            model_name='appuser',
            name='appuser_created_3324af_idx',
        ),
        migrations.RemoveIndex(
            model_name='appuser',
            name='appuser_last_up_a565c4_idx',
        ),
        migrations.RemoveIndex(
            model_name='customerrelationship',
            name='customer_re_appuser_1d4254_idx',
        ),
        migrations.RemoveIndex(
            model_name='customerrelationship',
            name='customer_re_points_149dae_idx',
        ),
        migrations.RemoveIndex(
            model_name='customerrelationship',
            name='customer_re_created_4d9583_idx',
        ),
        migrations.RemoveIndex(
            model_name='customerrelationship',
            name='customer_re_last_ac_78a740_idx',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='customer_id',
            field=models.CharField(default=contacts.models.generate_customer_id, editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customerrelationship',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['country', 'city'], name='address_country_1a8042_idx'),
        ),
    ]
